# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: compendium_development
  username: <%= ENV['COMPENDIUM_DB_USERNAME'] %>
  password: <%= ENV['COMPENDIUM_DB_PASSWORD'] %>
  

test:
  <<: *default
  database: compendium_test
  username: <%= ENV['COMPENDIUM_DB_USERNAME'] %>
  password: <%= ENV['COMPENDIUM_DB_PASSWORD'] %>

production:
  <<: *default
  database: compendium_production
